### ISSUE TITLE
Vault based configuration 

### ISSUE THREAD

**Issue by ggsood** [configu/configu#124]
**Description**
Hashicorp vault is widely used a mechanism to store secrets and with increasing environments having the ease to manage that in vault will be really helpful.

**Motivation**
Secret and configuration with Hashicorp vault will be a really welcoming feature.

**Comment by jamesL92** [comment]
From what I can tell this is currently supported in Node runtimes: https://github.com/configu/configu/blob/main/ts/packages/node/src/stores/HashiCorpVault.ts

I probably wouldn't add this to browser due to the security implications of it being misconfigured, although I think this would definitely make sense for python too. I've started working on the basis of supporting it in #126 , if/when that makes it through I could have a go at adding in Hashicorp Vault support.

**Comment by rannn505** [comment]
@ggsood Were you able to get Configu to work as you expected with HC Vault?
Is there anything else we can do to help you make a POC of the scenario? It would be great if you could contribute it to the repository as an example.

We would appreciate hearing from you 🙏🏽 .
