### ISSUE TITLE
Implement `INI` `ConfigStore` in Node.js SDK

### ISSUE THREAD

**Issue by rannn505** [configu/configu#152]
**Description**

- Plan a `Config` accommodation in the ini file.
- Add `INIConfigStore` class to the Node.js SDK stores.
- A quick search indicates that [ini](https://www.npmjs.com/package/ini) library is the most "suitable" for use during implementation.
- We would be happy to hear more suggestions, or we can implement the APIs ourselves.

**Motivation**

Extending Configu's [available stores](https://configu.com/docs/config-store/#available-stores) collection.
This ConfigStore will be made available in the Configu CLI since the Node.js SDK is used internally.

**Additional context**

- https://en.wikipedia.org/wiki/INI_file
- https://configu.com/docs/config-store/
- https://github.com/configu/configu/blob/main/types/ConfigStore.ts
- https://github.com/configu/configu/tree/main/ts/packages/node/src/stores

![image](https://github.com/configu/configu/assets/11806915/e603c3c3-703c-46d2-91a6-3c308089a8ce)

**Comment by RichardAkman** [comment]
## Suggested INI ConfigStore implementation

To ensure the INI ConfigStore implementation works seamlessly with standard usage of `INI` files, I propose the following strategy as explained below.

### General approach
[A standard INI file is composed of key-value pairs that are optionally aggregated by sections](https://en.wikipedia.org/wiki/INI_file). We can leverage the innate capabilities of INI files to implement Configu's `ConfigStore` paradigm as follows:
- The Config `key` and `value` properties naturally fit the key-value elements of INI files.
- The Config `set` property can be represented using the section element of INI files. Root-level key-value pairs would belong to the root set, this could be true for an empty string section `[]` for the sake of consistency.

### Implementation
We can leverage the highly popular [INI npm package](https://github.com/npm/ini) to implement this store. Here are some suggestions on how to implement the `ConfigStore`.

#### Initializing the store instance
Much the like `JsonFile` ConfigStore, this ConfigStore also uses a file as a store, which means we can leverage the same initialization logic as the `JsonFile` ConfigStore.

#### `get` method
We can utilize the `ini` package `decode` method after reading the file content using `fs.readFile` and forwarding the result. This will give us an object we then need to map into a `Config` array and then forward to the `Convert.toConfigStoreContents` method. We can encapsulate this logic as a `read` method similar to the `JsonFile` ConfigStore.

Notes:
- A value may be an array, this isn't currently supported by Configu because values need to be deterministic and there's no way for the user to explicitly ask for an index. Hence, array values should be omitted.

We can then use the `read` method as explained above and fetch the configs we want using the same `get` logic as the `JsonFile` ConfigStore.

#### `write` method
We want to maintain the upsert paradigm which means we want to first read all the content of the `ini` file which we can do using the `read` method as explained above. Once we have all the stored configs, they can be merged with the new configs, the result should have configs with empty values omitted and then the result can be converted into an object where each set is a key that contains the key-value pairs of the set. This object can be given to the `encode` method of the `ini` package and then be written back into the file.

Notes:
- Root level keys must be written to the top of the ini file before the first section, otherwise, the parsing in the `get` method will not work properly for the root set because the root level configs will belong to a different set accidentally.

#### Additional consideration

This strategy will provide a very solid basis for how this ConfigStore should operate but has the following drawbacks that should be addressed at some point:
- Any existing INI file that has comments will lose its comments after the `set` method is used on it.
- Arrays would not be supported in this implementation. Any `ini` file that's used with this store will lose any array values to ensure deterministic behavior.
