### ISSUE TITLE
FileStorage stores creates the file if not exists

### ISSUE THREAD

**Issue by RonConfigu** [configu/configu#156]
**Description**
With the new `FileStorageConfigStore`(temp name for ref) CSV and JSON and other files should be created by the store if the file doesn't exists

**Motivation**
This will help the user with the structure of the file. for example, CSV will most likely have default headers and JSON will be created with empty array

**Additional context**
https://github.com/configu/configu/issues/151
https://github.com/configu/configu/issues/151#issuecomment-1619782423

# Tasks

- [x] TS/Node SDK implementation
- [ ] Python implementation
- [ ] Go implementation

**Comment by rannn505** [comment]
@RonConfigu I would suggest that those file will be initiated with the required "empty state" based on their types.
For example `[]` (empty array) in json, or `set, key, value` headers in csv etc.

**Comment by RichardAkman** [comment]
To give a holistic solution to this issue, we should establish a baseline for how all file config stores should work. To this end, here is my proposal for a `FileConfigStore` that will serve as an abstract base class that all file ConfigStores (JSON, INI, CSV, etc...) will extend.

## Initialization

The main motivation behind this issue is the fact that until now, all file config stores did not aptly handle the scenario where the file does not exist. To handle this, we will leverage the `init` method in the base `ConfigStore` class.

The `FileConfigStore` will extend abstractly implement the `init` method, forcing any class that extends `FileConfigStore` to implement file initializtion. This will be highlighted with a comment. All relevant commands already perfom `store.init()` so this strategy is a natural approach.

Each file store has it's own way of storing data, for example JSON files store configs as an array of config objects whereas INI files store the data as key-value pairs under sections. Due to this, the `init` method in `FileConfigStore` cannot handle this logic because we can never know what the initial state of an "empty" file config store is, it's specific to the nature of the specific file that is in question.

## The `Get` and `Set` methods
The `Get` and `Set` methods are generic and aptly fit any type of file config store. All that is required from a file config store is to implement the `read` and `write` methods that will be used by `Get` and `Set`.

## `Read` method

The read method is an abstract method that all file config store will have to implement. This method reads the content of the file and parses the data into an array of configs which will be used by the `Get` method to return the desired configs and by the `Set` method to make maintain existing configs.

## `Write` method

The write method is an abstract method that all file config store will have to implement. This method converts configs into a format that fits the specific file store.

## Other considerations

- Because we are discussing file config stores, the abstract FileConfigStore is only relevant to backend usage and therefore only relevant to the Node SDK and SDKs in other programming languages
- The class does not know how data inside the files looks like, hence it cannot peform generalized validation. Validation should be implemented by classes that extend `FileConfigStore`.

**Comment by RichardAkman** [comment]
needs python and go implementation

**Comment by RichardAkman** [comment]
This issue is no longer relevant due to the Python and Go SDKs being deprecated in favor of `@configu/proxy`
