### ISSUE TITLE
Misleading error during RegEx type value validation

### ISSUE THREAD

**Issue by shini4i** [configu/configu#164]
**Actual behavior**
An error returned while upserting a value that does not match the `RegEx` pattern is misleading.
`Error: invalid config value "test.example.com" for key "DOMAIN" at UpsertCommand.run, value "test.example.com" must be of type "RegEx"`

**To Reproduce**
Create a project configuration file with the following content:
```
{
  "DOMAIN": {
    "type": "RegEx",
    "pattern": "^[a-zA-Z0-9-]{1,63}\\.[a-zA-Z]{2,}$"
  }
}
```
And run the following command:
`configu upsert --store 'configu' --set 'test' --schema './project-config.cfgu.json' -c 'DOMAIN=test.example.com'`

**Expected behavior**
I believe that the error should indicate that provided value should match the configured pattern instead of being of type `RegEx`

**Comment by rannn505** [comment]
@shini4i Your observation about the RegEx error message is accurate; it's indeed very misleading. The message could be improved to make it more explicit that the string value provided needs to match the specified regular expression, not that the value itself should be a regex. As you suggested something like: "... must match the pattern ${pattern}" would be a clearer error message. The fix is relatively straightforward - adding another conditional check in the EvalCommand logic [here for the ts SDK](https://github.com/configu/configu/blob/main/ts/packages/ts/src/commands/EvalCommand.ts#L223).
