### ISSUE TITLE
ExportCommand Key Mutation Callback

### ISSUE THREAD

**Issue by rannn505** [configu/configu#333]
### Suggestion

Introduce a new optional property of the `ExportCommand` called `keys` where users can provide a callback function `(key: string) => string`. This function will take a `configKey` as a string, apply desired mutations (like adding a prefix or suffix), and return a modified key to be used in the export result.

### Motivation

- This addition will enable functionalities such as `--prefix` or `--suffix` in the export command of the CLI, allowing for more versatile command options.
- Adapting keys on export is a common practice in application configuration management, enhancing flexibility for different environments.
- It accommodates specific requirements of some compilers or builders that necessitate particular prefixes for environment variables.

**Comment by RonConfigu** [comment]
## Development Plan
- [ ] Add the param to `EvalCommandParameters`
- [ ] Implement transform - until Q.1 & Q.3 is answered - in a new method `applyKeys` and return original key if anything goes wrong)
- [ ] depending on the answer to Q.2, some adjustments to `evalTemplates` may be necessary.

## Questions
1. Should the action take place in `evalTemplates` or in a new method? if in a new method. my suggestion is `applyKeys` @rannn505 @RichardAkman
2. Should I be able to declare transformed-keys in templates? @rannn505
3. What is expected to happen when the transform-method provided by the user throw exeption and or returns non-string value? @rannn505 @RichardAkman
3. Am I expected to implement in Python as well as part of this task? @RichardAkman
4. I assume the prop is optional? @rannn505

## Test Cases
1. Use the param via Node SDK with valid function
2. Use the param via Node SDK with invalid function
 - returns empty string
 - returns non-string
 - returns key that already exists in the result
 - raise exeption

### Notes / Comments / Additionals
Questions 1-3 should have been addressed beforehand and included in the issue. These pertain to product design rather than implementation.

**Comment by RichardAkman** [comment]
@RonConfigu My thoughts regarding the questions you raised:
1. I think that the logic for mutation should be separate from the evaluation logic. It should either happen before or after the template evaluation in a method as you've suggested.
2. You should be able to declare anything you want. The real question is whether the mutated keys are used for template evaluation. I believe they should be, but we need product input from @rannn505.
3. I feel strongly that the eval command should throw an exception if the provided function errors. If the user wants to mutate his keys but his function fails, he needs to be made aware so that he can fix it. 
4. The property should definitely be optional, I'm quite certain that's what Ran intended in the issue description. @rannn505 please confirm.
5. Please provide input on the Python implementation of this feature @rannn505.
6. I think that the mutation is intended to replace the previous keys. Perhaps we could consider making an option to let the user decide if they should be replaced or added. Please confirm @rannn505.
7. I think we should maintain the existing logic of the Eval command. Currently, if you provide duplicate keys, the "last" key overrides all the others. As the keys are iterated during the mutation, we can use the natural order of the keys and override any duplications. Please let me know what you think @RonConfigu and please confirm the intended behavior @rannn505.

Additional test cases:
- The mutation creates invalid keys that aren't normally allowed (`NAME` validation), example:
```
(key) => `!${key}}`
```

**Comment by rannn505** [comment]
@RonConfigu, the focus here is solely on the `ExportCommand`, indicating no relevance or required changes to the `EvalCommand`. It wasn't mentioned in any part of the issue, title, or description. Could you clarify how you perceived that changes to `EvalCommand` were necessary? Your insight on this misunderstanding would be valuable.

1. **EvalCommand Changes**: No changes should be made to `EvalCommand`. Also this question relates to implementation specifics rather than product-level decisions so it should be discussed with @configu/dev.
2. **Transformed Keys**: The keys should undergo evaluation first, and key mutations are applied only during export, provided a valid `keys` function is supplied.
3. **Function Validation**: Absolutely, there should be validation of the function before its application.
4. **Optional Property**: Yes, the `keys` parameter is optional in `ExportCommand`.
5. **Python Implementation**: Not required at this stage, unless it is really short (ie. 1-2h) cc @pelegpor .
6. **Original Keys**: The purpose of mutations is to transform the keys, so retaining original keys isn't necessary. For example, a mutation might prepend `REACT_APP_` to a key for Create React App usage.
7. **Specific Case Handling**: In the scenario you provided, the result should be one key, "ME", with the last value of the export.
8. **Documentation**: The documentation at oss.configu.com is auto-generated. However, the new parameter should be documented in `ExportCommand` on configu.com/docs.
9. **`utils.NAME()` Function**: Yes, the mutated key should pass through the `utils.NAME()` function.

Let me know if there are any more queries or clarifications needed!

cc @pelegpor @RichardAkman

**Comment by RonConfigu** [comment]
## Development Plan
- [x] Add `keys?: (key: string) => string;` to `ExportCommandParameters`
- [x] Implement `mutateKeys` in ExportCommand - The function will try to use the provided 'keys' function and pass its return through `util.NAME()`. If everything is ok the muteted key is returned otherwise the original key.
- [x] Create Test Units
- [ ] Update docs (if necessary)

## Questions / Requests

## Test Units
#### Valid Tests
- [x] Export without keys mutation callback
- [x] Export with keys mutation callback
#### Invalid Tests
- [x] Export with bad keys mutation callback - returns empty string
- [x] Export with bad keys mutation callback - returns non-string
- [x] Export with bad keys mutation callback - returns !NAME()
- [x] Export with bad keys mutation callback - raise exception


### Notes / Comments / Additional

**Comment by RichardAkman** [comment]
@rannn505 this feature wasn't implemented in the Python and Go SDKs. Letting you know in case you want to reopen this issue or create a new one for those SDKs.
