### ISSUE TITLE
Implement Local Cache for ConfigStore

### ISSUE THREAD

**Issue by rannn505** [configu/configu#370]
### Suggestion
We propose the integration of a local caching mechanism for ConfigStore which will significantly enhance performance by reducing fetch times and providing a fallback during outages. This cache should be configurable via the `.configu` file, allowing users to toggle caching on or off, or specify a custom SQLite file for the cache data.

- Add an optional string `cache` property to root of the `.configu` file.
- Add an optional boolean `cache` property under `stores.[storeName].cache` of the `.configu` file.
- Enable local cache if one of the `stores.[storeName].cache` props are true. -> this enables the cache for that spesific store. 
- If there arent any stores with cache: true, disable cache.
- if a custom path string is provided to the root cache prop -> use the specified SQLite file otherwise use the default cache path at `$cacheDir/configs.sqlite`:
- Automatically save to cache after each successful `eval` command execution involving that ConfigStore.
- In case of a ConfigStore fetch error during `eval` (not an actual eval error like validate the cfgu against a Config), attempt to fetch the Config from the local cache if caching is enabled.
- Add a `--force-cache` flag to the `eval` CLI command to allow fetching Configs strictly from the cache.

### Motivation
Introducing a local cache for ConfigStore aims to:
- Minimize latency during configuration fetch operations.
- Provide resilience against temporary ConfigStore outages or network issues.
- Streamline CI/CD processes by allowing cache artifacts to be saved and reused, improving build times and reliability.

### Context
Additional considerations include:
- Ensuring cache integrity and freshness—cache should be updated or invalidated based on configurable criteria.
- Testing within CI environments like GitHub Actions to confirm the cache's effectiveness as a stored artifact and its reusability across multiple build runs.
- Establishing a clear cache management strategy for users to understand when and how cache is utilized or ignored.

**Comment by rannn505** [comment]
Suggestion:
We propose the integration of a local caching mechanism for ConfigStore which will significantly enhance performance by reducing fetch times and providing a fallback during outages. This cache should be configurable via the `.configu` file, allowing users to toggle caching on or off, or specify a custom SQLite file for the cache data.

- Add a `cache` property to `.configu` file under `stores.[storeName]`. This can be a boolean or a string.
- When `true`, use the default path `$cacheDir/configu/$storeName.sqlite`.
- When `false`, caching for that store is disabled.
- If a custom path string is provided, enable caching and use the specified SQLite file.
- Automatically save to cache after each successful `eval` command execution involving that ConfigStore.
- In case of a ConfigStore error during `eval`, attempt to fetch the Config from the local cache if caching is enabled.
- Add a `--force-cache` flag to the `eval` CLI command to allow fetching Configs strictly from the cache.

Motivation:
Introducing a local cache for ConfigStore aims to:
- Minimize latency during configuration fetch operations.
- Provide resilience against temporary ConfigStore outages or network issues.
- Streamline CI/CD processes by allowing cache artifacts to be saved and reused, improving build times and reliability.

Context:
Additional considerations include:
- Ensuring cache integrity and freshness—cache should be updated or invalidated based on configurable criteria.
- Testing within CI environments like GitHub Actions to confirm the cache's effectiveness as a stored artifact and its reusability across multiple build runs.
- Establishing a clear cache management strategy for users to understand when and how cache is utilized or ignored.

**Comment by RonConfigu** [comment]
## Development Plan
- [x] Modify `SQLiteConfigStore` so that the table is dynamic
- [x] Add `cache?: boolean | string` to `BaseConfig`
- [x] Create `getCacheStoreInstanceByStoreFlag` to `BaseCommand`. Adding to base and not to eval for future uses in cache in other commands.
- [x] Create `class ConfigStoreError extends ConfigError {}` to identify errors from the store
- [x] Modify `ORMConfigStore` to except `tableName` in params
- [x] Modify `SQLiteConfigStore` to except `tableName` in params
- [x] Modify `EvalCommand` to throw `ConfigStoreError` where:
  - [x] `store.init()` throws
  - [x] any error inside `evalFromStoreSet`
  - [x] `validateResult` throws and the origin is `EvaluatedConfigOrigin.StoreSet`
- [x] Implement caching and fetch from cache in cli eval
- [x] Add `--force-cache` to cli eval
- [ ] Create UnitTests
- [ ] Update docs (if necessary)

## Questions / Requests

### Notes / Comments / Additional

**Comment by rannn505** [comment]
`cache` on the main base-config with the file path and cache on each store with enable disable for it.
<img width="1095" alt="image" src="https://github.com/configu/configu/assets/11806915/d36692f7-a47c-4250-a008-2e92cc37afb4">

if any store is "cache enabled" and the file path is not defined use the default one.
I will fine tune the ticket now so it reflects the final product request

**Comment by rannn505** [comment]
please attach the .configu, .cfgu and GH action workflows file of the test you created here @RonConfigu

**Comment by RichardAkman** [comment]
An initial implementation of this feature has been implemented and released to both `@configu/node` & `@configu/cli`. The implementation is currently missing the cache fallback requirement from this issue due to a concern raised during the product review where authentication errors also caused cache fallbacks that go against the product vision. Masking authentication errors should be allowed only if the user explicitly asks for it. Until we come back to the issue, we have disabled the fallback mechanism on the SDK level. Once we determine the definitions of authentication errors on a store-level, we will return to this issue and implement the requirements fully.

**Comment by RonConfigu** [comment]
> please attach the .configu, .cfgu and GH action workflows file of the test you created here @RonConfigu
Sure, files with txt because GH doesn't allow these file types
[cache.cfgu.json](https://github.com/configu/configu/files/14997263/cache.cfgu.json)
[dot-configu.txt](https://github.com/configu/configu/files/14997284/do
[gh.yaml.txt](https://github.com/configu/configu/files/14997292/gh.yaml.txt)
t-configu.txt)
