### ISSUE TITLE
Implement `key-value` stores

### ISSUE THREAD

**Issue by rannn505** [configu/configu#40]
**Description**

Building a unified infrastructure for key value-type stores and migrating all "old" secret-typed integrations to this infrastructure.

**Motivation**

- Allow users to read and write secrets from a variety of different secret providers.
- Add another store to the browser SDK apart from Configu Store

**Additional context**

@configu/ts:
- [x] Implement a base interface that enables I/O capabilities against databases built in key-value format.

@configu/node:
- [x] HashiCorp Vault
- [x] AWS Secrets Manager
- [x] Azure Key Vault manager
- [x] GCP Secret Manager
- [x] Kubernetes Secrets
- [x] [Localforage Store](https://github.com/localForage/localForage)

@configu/cli:
- [x] HashiCorp Vault
- [x] AWS Secrets Manager
- [x] Azure Key Vault manager
- [x] GCP Secret Manager
- [x] Kubernetes Secrets

**Comment by RichardAkman** [comment]
Localforage will not have a CLI implementation as it can only be used within a browser environment which the cli cannot communicate with.

**Comment by RichardAkman** [comment]
# Background regarding the decision to implement `key-value` stores
While implementing secret manager stores there were a few recurring issues that kept resurfacing that caused code duplication and also exposed additional issues that weren't taken into consideration in the existing logic. Secret managers stores typically store data in a key-value format. This fact resulted in a few recurring issues when implementing any new key-value store.

## Code duplication of existing get/set methods
Key value stores have a lot of shared logic within the 'get' and 'set' methods. This naturally means that key-value stores should all inherit the shared logic from a new class that they all inherit from. This class should naturally be called something similar to "KeyValueStore". This store class remains abstract because the low-level implementation of the get/set logic changes based on the API of the implemented store.

## Converting schemas/sets/keys to key-value pairs
Configu stores configurations using a provided schema and given set. The schema and set are used to uniquely identify each configuration key that is stored. The nature of key-value stores forces us to determine how to convert schemas, sets, keys, and their value to a key-value pair. These are the options:
1) An arbitrary key ("Configu" for instance) is used as a 'key' and all the data is somehow stored in the 'value'. 
2) Either the schema, set, or key serves as the 'key', and the unused properties are somehow stored together with the value in the 'value'.
3) A combination of schema/set, schema/key, or set/key is used as the 'key', and the unused property is somehow stored together with the value in the 'value'.
4) A combination of the schema, set, and the key is used as the 'key' and the value is stored as is in the 'value.

Each of the aforementioned options has cons and pros, which include:
- Store limitations on the 'value' size. For example, Google Secret Manager supports secret values up to 64 KiB. This incentive us to minimize the data stored within the 'value', which favors options 3 & 4.
- Transparency of how data is stored within the user's store. Storing data using a user-provided store in such a way that is unfriendly to the user and is not transparent reduces the user's trust in our platform. This encourages us to keep the key and the value as human-readable as possible, which favors options 3 & 4.
- The cost of data storage. For example, Google Secret Manager charges per active secret version. This incentive us to minimize the amount of key-value pairs, which favors options 1 & 2.
- Efficiency of operations. The more key-value pairs we generate, the more API requests we must make to the store. This naturally affects the speed of each command though this is minimized by using async logic that makes these requests in parallel, the bigger issue is the cost of each of these requests which might be significant depending on the store. For example, Google Secret Manager charges 0.03$ per 10k operations. This incentive us to minimize the amount of key-value pairs we generate (having us do the dirty work using our own code), which favors options 1 & 2. 
- Alignment with existing key-value pairs not generated by Configu. Perhaps the most tricky conundrum, each user stores his own key values in any way he sees fit and we would like to match their own style of data storage which would make using our interface as seamless as possible. Unfortunately, we can never know or assume the user's style of data storage which means we need to either arbitrarily pick whatever we think is best for them (which may change depending on the store) or let them pick which option they prefer.

As it stands, option 3 is currently implemented where set/schema is used as the key. It would seem that the ideal solution would be to let the user decide how to have us store the data but this required additional implementation.

Regardless, the key-value store class is forced to implement logic that determines how to assemble the necessary 'keys'. This logic is inherently inelegant because stores expect a variation of a key that matches their own limitation as will be mentioned next.

## Arbitrary character limitations on the 'key' of key-value stores
Many of the key-value stores have an arbitrary limitation on what characters are legal within the 'key'. For example, Google Secret Manager does not allow the character '/' within the key. These limitation force the store implementation to do unpleasant manipulations on the key to ensure that the key is valid. These limitations are seemingly universal among all secret managers and that fact implies that this logic should be handled across the board via the key-value store class.

## Some stores require additional credentials
Some stores require additional parameters to access their data. This naturally forces us to require additional input from the user when they initialize their store class or for them to supply us with the details via some other means. For example, Hashicorp requires a specified 'engine' and Google Secret Manager requires a `projectId`. As it stands, it was decided to supply these additional parameters via the Set class, this resulted in unpleasant issues:
- The "root" set causes the get method to fail, this required us to define what the 'root' set is within the context of each store.
- Store protocols became convoluted and arbitrary by forcing additional details on the <query> part of the reference.

The natural approach to simplify the implementation is to have the constructor of the store class accept configurations and have each store determine which configurations are valid. In terms of the store protocol structure, additional parameters should be attached as query parameters. This will require the CLI parser to adjust the parsing and apply these additional parameters.

For now, we assume that the user provides a store that matches their references. Later we should consider allowing these parameters on references and somehow route these references to the correct store instance.

## Reference values are ambiguous regarding how to access their data
References do not tell us anything about the nature of how the reference data is stored, only the target store type and some string that is given to us to access the data. This is especially problematic with `key-value` stores because we don't know how the values are stored as there's no standard. We want to have an interface that supports references to values regardless of how they are stored and their data type. The following issues come to the surface:
- References do not indicate the data type of their values. There is no standard data type that all stores support. This forces us to either make assumptions on the data type, return the value as it is stored which might be unpleasant for users to work with, or get input from the user regarding the data type so we may attempt to parse it correctly. This issue is compounded by the fact that we do not know if the reference is to a value that is managed by Configu or not, which means that if we need parsing for Configu-managed values we might right into issues at worst or may need to ask the user how to parse our own data which is weird at best (can be mitigated if we let the user decide how we store our managed data).
  - Identifying reference data types: using dot notations to indicate key access or using a query param that explicitly states how we access the data
  - Identifying who stores the data: either explicitly ask who manages the data (one of the options may be a default for better UX) or force the user to be explicit with the data access (requires the user to know how we store configu managed data)
- Reference queries need to be somehow parsed into a Store Query instance but this only makes sense within the context of data stored by configu. This may be solved by letting the store assemble the query into a way to access data on an individual basis.
