### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by gevaperry** [configu/configu#417]
Path: /introduction/overview

The link to Guides in the nav menu just goes to the overview
<img width="194" alt="image" src="https://github.com/configu/configu/assets/59607/f4c4b81b-450f-462c-ae5b-0e442a80436b">

**Comment by rannn505** [comment]
Hi @mohanchand201,

Thanks for offering to jump in on this issue! I'm currently in the middle of stabilizing the new docs portal and have addressed this particular problem. However, your keen eye would be super helpful in spotting any other potential issues! Feel free to take a look around and suggest fixes where you see fit. Your contributions are very much appreciated!

---

Hey @gevaperry,

Thanks for pointing this out! It’s been fixed in the latest updates to the docs portal. If you notice anything else that needs tweaking, please don't hesitate to let us know. Your feedback is invaluable to us!

**Comment by rannn505** [comment]
Hi @mohanchand201,

Thanks for offering to jump in on this issue! I'm currently in the middle of stabilizing the new docs portal and have addressed this particular problem. However, your keen eye would be super helpful in spotting any other potential issues! Feel free to take a look around and suggest fixes where you see fit. Your contributions are very much appreciated!

---

Hey @gevaperry,

Thanks for pointing this out! It’s been fixed in the latest updates to the docs portal. If you notice anything else that needs tweaking, please don't hesitate to let us know. Your feedback is invaluable to us!
